person:
  name: wj
  age: 22
  list:
    -a
    -b
    -c
  dog:
    name: 肥猪
    age: 1

server:
  port: 8080
spring:
  profiles:
    active: dev

---

server:
  port: 8081
spring:
  profiles: dev

---

server:
  port: 8082
spring:
  profiles: test